name: Build and Release

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write


jobs:
  build:
    runs-on: windows-latest   # build exe trÃªn Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Debug requirements.txt
      run: cat requirements.txt
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Show Installed Packages
      run: pip list

    - name: Build EXE
      shell: pwsh
      run: |
        pyinstaller --onefile main.py
        mkdir release
        Copy-Item dist\*.exe release\
    - name: Test EXE 
      shell: pwsh 
      run: | 
        ./release/main.exe --help

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ github.run_number }}
        name: Windows Release v${{ github.run_number }}
        files: |
          release/**/*.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
